openapi: 3.1.0
info:
  title: Alice OneNote Logger
  version: 1.0.0
  description: Create a page in AliceChatGPT/Inbox, read back the text, and return OneNote links.
servers:
  - url: https://alice-onenote-router.vercel.app
paths:
  /api/graph/create-read-link:
    post:
      summary: Create a page in Inbox, read text, and return links
      operationId: createReadLink
      security:
        - ServiceBearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                html:
                  type: string
              required: [title, html]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  created:
                    type: object
                    properties:
                      id:
                        type: string
                  text:
                    type: string
                  links:
                    type: object
                    properties:
                      oneNoteWebUrl:
                        type: string
                      oneNoteClientUrl:
                        type: string

components:
  securitySchemes:
    ServiceBearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - ServiceBearerAuth: []
