openapi: 3.1.0
info:
  title: Alice OneNote Logger
  version: "1.0.0"
servers:
  - url: https://alice-onenote-router.vercel.app
paths:
  /api/chat/log:
    post:
      operationId: logNote
      summary: Append a natural-language entry to the user’s OneNote daily page.
      security:
        - ServiceBearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [text]
              properties:
                text:
                  type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  pageId:
                    type: string
                  title:
                    type: string
  /api/chat/today:
    get:
      operationId: getToday
      summary: Get today’s OneNote daily log text.
      security:
        - ServiceBearer: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  id:
                    type: string
                  title:
                    type: string
                  text:
                    type: string
components:
  securitySchemes:
    ServiceBearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
