openapi: 3.1.0
info:
  title: Alice OneNote Logger
  version: 1.0.0
  description: Create a page in AliceChatGPT/Inbox, read back the text, and return openable links.
servers:
  - url: https://alice-onenote-router.vercel.app
paths:
  /api/graph/create-read-link:
    post:
      summary: Create a page in Inbox, read text, and return links
      operationId: createReadLink
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title, html]
              properties:
                title:
                  type: string
                  description: Page title to create
                html:
                  type: string
                  description: HTML body (<p>…</p>)
      responses:
        "200":
          description: Page created and resolved
          content:
            application/json:
              schema:
                type: object
                required: [ok, created, text, links]
                properties:
                  ok:
                    type: boolean
                  created:
                    type: object
                    required: [id]
                    properties:
                      id:
                        type: string
                        description: OneNote page id
                  text:
                    type: string
                    description: First lines of the created page
                  links:
                    type: object
                    required: [oneNoteWebUrl, oneNoteClientUrl]
                    properties:
                      oneNoteWebUrl:
                        type: string
                      oneNoteClientUrl:
                        type: string
components:
  # Some Builder versions require `schemas` to exist and be an object
  schemas: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
